package utils;

import java.util.Random;

public class NameGenerator
{
    public static final String[] titles = {
        "Republic of ",
        "Empire of ",
        "United ",
        "Kingdom of ",
        "Republic of ",
        "Empire of ",
        "United ",
        "Kingdom of ",
        "North ",
        "South ",
        "East ",
        "West ",
        "Eastern ",
        "Western ",
        "Dominion of ",
        "Dominion of ",
        "Dominion of ",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };

    public static final String[] names = {
        "Waskuavania",
        "Echeuyae",
        "Meswium",
        "Peclos",
        "Snuyque",
        "Choycia",
        "Aflua",
        "Aprain",
        "Droy",
        "Brium",
        "Tru",
        "Scya",
        "Doglaocor",
        "Dofreutan",
        "Powheau",
        "Motral",
        "Draetho",
        "Blaria",
        "Efleau",
        "Atrain",
        "Thaej",
        "Snea",
        "Swuyp",
        "Praria",
        "Qoclole",
        "Muskioya",
        "Yocharia",
        "Ubryae",
        "Bruissau",
        "Strairhiel",
        "Eswait",
        "Etrain",
        "Chue",
        "Swor",
        "Druec",
        "Scines",
        "Buploze",
        "Yaclele",
        "Mowhana",
        "Jaclium",
        "Swioji",
        "Swuejan",
        "Oglaria",
        "Eprium",
        "Friux",
        "Strela",
        "Shuev",
        "Flea",
        "Oskiyya",
        "Iuswugua",
        "Iaswington",
        "Xescax",
        "Sheajan",
        "Sheuze",
        "Atrea",
        "Uscea",
        "Criej",
        "Whein",
        "Sheum",
        "Swea",
        "Lodroacor",
        "Juflueles",
        "Jochary",
        "Jufron",
        "Snuesil",
        "Skeuna",
        "Edren",
        "Ustyae",
        "Driyb",
        "Snain",
        "Chuyi",
        "Whary",
        "Quthoarus",
        "Yacheuria",
        "Zucrain",
        "Dotrington",
        "Criegro",
        "Struonia",
        "Ucristan",
        "Awhela",
        "Fruym",
        "Snistan",
        "Droub",
        "Glua",
        "Jesciewana",
        "Gadraibia",
        "Fochad",
        "Joskistan",
        "Triyqua",
        "Stioles",
        "Askia",
        "Asteau",
        "Grex",
        "Smar",
        "Cluos",
        "Spines",
        "Begruilia",
        "Jufroayae",
        "Asmington",
        "Vostrium",
        "Theycia",
        "Pleynia",
        "Ushington",
        "Ucrea",
        "Cruoj",
        "Swyae",
        "Dreoj",
        "Cleau",
        "Jathaistan",
        "Xeskeycia",
        "Gaskurg",
        "Ioclad",
        "Thoedan",
        "Fleucor",
        "Askistan",
        "Uskines",
        "Sho",
        "Swela",
        "Skaut",
        "Fla",
        "Febrole",
        "Ieskoinia",
        "Medra",
        "Oglington",
        "Sheque",
        "Skaulia",
        "Ocrijan",
        "Uscus",
        "Scuaf",
        "Scurg",
        "Stroyh",
        "Chad",
        "Catiyana",
        "Codistan",
    };

    public static String GetRandomName(Random rand)
    {
        StringBuilder res = new StringBuilder(titles[rand.nextInt(titles.length)]);
        
        int num = rand.nextInt(3) + 1;
        for (int i = 0; i < num; i++)
        {
            res.append(names[rand.nextInt(names.length)]);
            if (i < num - 1) res.append(" ");
        }

        return res.toString();
    }
};